ros/genpy

- src/genpy/rostime.py
- test/test_genpy_rostime.py
Addresses #35.
@esteve @tfoote @wjwwood Please review.
> fix Duration.abs() when sec is zero and add a test for it

- src/genpy/message.py
This change ensures that the nsecs field is always right aligned such that the least significant digit of the  secs field aligns with the least significant digit of the secs field. This makes it easier to inspect how far into the second the time has progressed.
Before:
```
stamp: 
secs: 1450885486
nsecs: 3398683
```
After:
```
stamp: 
secs: 1450885486
nsecs:   3398683
```
A minor aesthetic change, but this makes it easier to look for the start of a certain second, as well as easier to read because the values of the same significance are always on the same position.
Hopefully it doesn't break anyone's scripts relying on the output; there still is always a space after the semicolon, but below the 100ms there are multiple spaces between the semicolon and the number.
> Align the nsecs field of the timestamps.

- test/test_genpy_message.py
The alignment of the nsecs field was changed in ros/genpy@edb9c5abf2b4fe7d716ae8fa72cceb24717b0035
(pull request ros/genpy#45), this caused the regression test for
the timestamp field to fail.
This commit updates the comparison value of the regression tests to reflect
the new alignment.
> Update regression test for nsecs alignment.

- src/genpy/generate_initpy.py
Whilst working on the "reproducible builds" effort [0], we noticed that
genpy generates output with a non-determistic order.
The attached patch removes this randomness from the build system. Once
applied, packages using python-genpy can be built reproducibly using our
reproducible toolchain.
[0] https://wiki.debian.org/ReproducibleBuilds
Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>
> Please make generated __init__.py files reproduducible

- src/genpy/rostime.py
- test/test_genpy_rostime.py
Fixes #49.
This adds a `RuntimeWarning` for using floor division with integer dividers. Imo it is reasonable to add this warning to all supported distros since it is informing the user that something unexpected is going on. I don't see a use case where this behavior is actually intended. If existing code currently uses this it will result in a warning and the code an easily be updated.
Regarding the question if the class should always implement true division (for all or only newer ROS distros): Python has the same situation when doing integer division. Some might call it really bad default behavior but that's how Python does it. And there is a clean way (`from __future__ import division`) to explicitly use true division (which is the same across division operations across various types). …
> warn about using floor division of durations

- src/genpy/generator.py
- test/test_genpy_generator.py
For an example field `uint32[10] foo` the generated code look as follows:
Without this patch: `self.foo = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]`
With this patch: `self.foo = [0] * 10`
And now imagine `N` being `134217728` as in ros/ros_comm#808 :bomb:
I would propose to also backport this patch to Indigo and Jade after it has been merged.
> fix default value of lists to not expand to N items in the generated code

- src/genpy/generate_struct.py
- src/genpy/generator.py
- test/files/array/bool_fixed_deser.txt
- test/files/array/bool_fixed_ser.txt
- test/files/array/int16_fixed_deser.txt
- test/files/array/int16_fixed_ser.txt
- test/files/array/object_fixed_deser.txt
- test/files/array/object_fixed_ser.txt
- test/files/array/object_varlen_deser.txt
- test/files/array/object_varlen_ser.txt
- test/files/array/object_varlen_ser_full.txt
- test/files/array/uint8_fixed_ser.txt
- test/files/array/uint8_fixed_ser_np.txt
- test/files/complex/object_ser.txt
- test/files/complex/object_ser_full.txt
- test/test_genpy_generate_struct.py
While this doesn't prevent the high memory usage for data structures with large static arrays it at least defers the initialization of the `Struct` until it is actually being used.
Related to ros/ros_comm#808
While this *does* change the API in the generated modules there is no way to keep it a variable but initialize it on demand. And since the variable is considered private (leading underscore) hopefully nobody uses it.
I would propose to **not** backport this patch (due to the internal API change).
> lazy init struct

- src/genpy/rostime.py
- test/test_genpy_rostime.py
Regressions from #63.
@eric-wieser FYI
> fix Python 3 regressions

- src/genpy/generator.py
- test/test_genpy_generator.py
Fix regression of #64 as reported in https://github.com/ros/genpy/pull/64#issuecomment-282599522
@ros/ros_team Please review.
> fix default value for non-primitive fixed-size arrays

- src/genpy/dynamic.py
Required for ros/ros_comm#1006.
@ros/ros_team Please review.
> expose spec for dynamically generated messages

- package.xml
- src/genpy/message.py
- test/test_genpy_message.py
Feeding output of "rostopic echo" back into "rostopic pub" does not work properly with strings containing characters which have special meaning in YAML (e.g. '#', "'" or '"').
These chars should be escaped properly to make the output of "rostopic echo" and the string representation of messages in general valid YAML code.
Strings are not properly escaped in strify_message, so publishing a string like e.g. 'foo # bar':
```
$ rostopic pub -1 /string std_msgs/String "data: 'foo # bar'"
```
results in YAML code where the string only contains "foo " and "# bar" is treated as a comment, changing the data without even raising an error:
```
$ rostopic echo /string
data: foo # bar
---
```
After applying this PR the correct result is printed
```
$ rostopic echo /string
data: 'foo # bar'
---
```
This …
> Add escaping for strings which is valid in YAML 

- src/genpy/generator.py
Hurd uses a different errno, so testing for the string as well.
> Fix exception handling on Hurd

- src/genpy/message.py
In Python3, running `rostopic echo` on a message with a `uint8[]` field prints the field as a bytes type without conversion to a list of numbers:
```
$ rostopic pub  /test std_msgs/UInt8MultiArray "data: [1,2,3]"
```
```
$ rostopic echo /test
layout: 
dim: []
data_offset: 0
data: b'\x01\x02\x03'
```
We need to explicitly handle this case for Python 3 since `bytes` is not the same as `str` in Python 3 so the `isstring` check does not handle it.
This change does not affect Python 2 since the checks in the first and the new branch are equivalent in Python 2 so it would never take the new branch.
> Fix _convert_getattr for handling uint8[] message fields in Python 3

- src/genpy/dynamic.py
- test/test_genpy_dynamic.py
Addressing this issue: https://github.com/ros/genpy/issues/94
The proposed workaround probably makes the function accept any binary data in comments. Not sure, if this is universally acceptable.
> Failing test case for UTF-8 encoded characters in comments

- src/genpy/message.py
Fixes #101 
e.g before the OK range was 127 to -127, now it is 127 to -128, which is correct.
> Fix negative limit check for signed ints

- package.xml
- setup.py
On Debian Buster and Ubuntu Focal [distutils has been split to a separate package](https://packages.debian.org/buster/python3-setuptools). With https://github.com/ros/catkin/pull/1048 catkin will prefer to use `setuptools` instead of `distutils`. Catkin [exports a buildtool depend for python3-setuptools](https://github.com/ros/catkin/blob/a3e97e4c7b34bded6e5055703f068e664ab88176/package.xml#L32), but it does not do the same for Python 2. Since this PR is targeting the `kinetic-devel` branch, it both switches to `setuptools` to match catkin's preference and adds a `<buildtool_depend>` on `python-setuptools` so it still works when `ROS_PYTHON_VERSION` is 2.
> Use setuptools instead of distutils

- src/genpy/dynamic.py
Calling `re.sub` results in significant overhead. Searching for `'.msg'` allows skipping the call when it is not needed.
> Small optimization in dynamic.py

- src/genpy/message.py
Where older PyYAML `dump(['', ''])` calls returned:
`['', '']\n`
newer versions return:
`- ''\n- ''\n`
This patch makes the logic support both.
> update logic for newer PyYAML output for dump()

- package.xml
- src/genpy/message.py
- test/test_genpy_message.py
Fixes #130.
Specifically, this PR improves the error messages during serialization. Consider the following script:
```python
from io import BytesIO
from geometry_msgs.msg import PoseStamped
msg = PoseStamped()
msg.pose.position.x = '0.0'
buff = BytesIO()
msg.serialize(buff)
```
**Old behavior:**
```
Traceback (most recent call last):
File "/opt/ros/noetic/lib/python3/dist-packages/geometry_msgs/msg/_PoseStamped.py", line 106, in serialize
buff.write(_get_struct_7d().pack(_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w))
struct.error: required argument is not a float
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```
> Add check for float32 and float64 to check_type

- src/genpy/generator.py
- src/genpy/message.py
Replaces #133 (since I didn't have permissions to push to the forked branch) and closes #132.
This patch makes the remaining code for the custom codec error handler conditional on the Python version.
@gwendolynbrook @mikepurvis FYI
> python3 guard for using rosmsg codec (take 2)

- src/genpy/message.py
This reverts the changes to `message.py` from #134. This PR makes the codec always be registered so that messages generated with genpy `0.6.14` continue to work when used with Python 2 and newer genpy versions.
Closes #138
> Revert #134 changes to message.py

- src/genpy/generate_struct.py
The function reduce_pattern only checks whether the current character in the format string is a number up to including 8. This causes a bug when reading ros messages containing an array which has a size that contains two consecutive 9s. This commit fixes this.
> Fix bug in reduce_pattern
